# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "aws-terraform-state-staging"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-east-1"
  }
}
