# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    # - repoURL: https://github.com/kusalindika/kubernetes
    #   targetRevision: HEAD
    #   ref: prometheus
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: 27.5.1
      helm:
        values: |
            server:
              service:
                type: ClusterIP
            serverFiles:
              alerting_rules.yml:
                groups:
                  - name: Instances
                    rules:
                      - alert: InstanceDown
                        expr: up == 0
                        for: 5m
                        labels:
                          severity: page
                        annotations:
                          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
                          summary: 'Instance {{ $labels.instance }} down'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true