apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.backendFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "test-app.backendLabels" . | indent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
{{ include "test-app.backendSelectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
