apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-app.frontendFullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "test-app.frontendLabels" . | indent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }

        location /api {
            proxy_pass http://{{ include "test-app.backendFullname" . }}.{{ .Release.Namespace }}.svc.cluster.local;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            access_log off;
            return 200 'ok';
            add_header Content-Type text/plain;
        }
    }
