{{- if and .Values.istio.enabled .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.peerAuthentication.mtlsMode }}
{{- end }}
